version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, go]
    groups:
      go-deps:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies, javascript]
    groups:
      npm-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, github-actions]

  - package-ecosystem: docker
    directories:
      - /
    schedule:
      interval: weekly
    labels: [dependencies, docker]
