// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package dbq

import (
	"context"
	"database/sql"
	"time"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, author_id, body, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateCommentParams struct {
	PostID   int64
	AuthorID sql.NullInt64
	Body     string
	ParentID sql.NullInt64
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.PostID,
		arg.AuthorID,
		arg.Body,
		arg.ParentID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM comments WHERE id = $1 AND author_id = $2
`

type DeleteCommentParams struct {
	ID       int64
	AuthorID sql.NullInt64
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteComment, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPostTitle = `-- name: GetPostTitle :one
SELECT title FROM posts WHERE id = $1
`

func (q *Queries) GetPostTitle(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getPostTitle, id)
	var title string
	err := row.Scan(&title)
	return title, err
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.post_id, c.author_id,
       COALESCE(u.display_name, c.author_name, 'Anonymous') AS author_name,
       u.avatar_path AS author_avatar,
       c.body, c.parent_id, c.created_at
FROM comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.post_id = $1
ORDER BY c.created_at ASC
`

type ListCommentsRow struct {
	ID           int64
	PostID       int64
	AuthorID     sql.NullInt64
	AuthorName   string
	AuthorAvatar sql.NullString
	Body         string
	ParentID     sql.NullInt64
	CreatedAt    time.Time
}

func (q *Queries) ListComments(ctx context.Context, postID int64) ([]ListCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.Body,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
