// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package dbq

import (
	"context"
	"database/sql"
	"time"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (uploader_id, filename, storage_path, thumbnail_path, mime_type, byte_size, width, height, attached_post_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type CreateMediaParams struct {
	UploaderID     sql.NullInt64
	Filename       string
	StoragePath    string
	ThumbnailPath  sql.NullString
	MimeType       string
	ByteSize       sql.NullInt64
	Width          sql.NullInt32
	Height         sql.NullInt32
	AttachedPostID sql.NullInt64
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.UploaderID,
		arg.Filename,
		arg.StoragePath,
		arg.ThumbnailPath,
		arg.MimeType,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.AttachedPostID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const getMediaForDelete = `-- name: GetMediaForDelete :one
SELECT storage_path, thumbnail_path
FROM media WHERE id = $1 AND uploader_id = $2
`

type GetMediaForDeleteParams struct {
	ID         int64
	UploaderID sql.NullInt64
}

type GetMediaForDeleteRow struct {
	StoragePath   string
	ThumbnailPath sql.NullString
}

func (q *Queries) GetMediaForDelete(ctx context.Context, arg GetMediaForDeleteParams) (GetMediaForDeleteRow, error) {
	row := q.db.QueryRowContext(ctx, getMediaForDelete, arg.ID, arg.UploaderID)
	var i GetMediaForDeleteRow
	err := row.Scan(&i.StoragePath, &i.ThumbnailPath)
	return i, err
}

const listMediaByUploader = `-- name: ListMediaByUploader :many
SELECT id, filename, storage_path, thumbnail_path, mime_type, byte_size, width, height, created_at
FROM media
WHERE uploader_id = $1
ORDER BY created_at DESC
LIMIT 200
`

type ListMediaByUploaderRow struct {
	ID            int64
	Filename      string
	StoragePath   string
	ThumbnailPath sql.NullString
	MimeType      string
	ByteSize      sql.NullInt64
	Width         sql.NullInt32
	Height        sql.NullInt32
	CreatedAt     time.Time
}

func (q *Queries) ListMediaByUploader(ctx context.Context, uploaderID sql.NullInt64) ([]ListMediaByUploaderRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByUploader, uploaderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaByUploaderRow{}
	for rows.Next() {
		var i ListMediaByUploaderRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.MimeType,
			&i.ByteSize,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
