// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: misskey.sql

package dbq

import (
	"context"
)

const getUserIDByMisskeyAccount = `-- name: GetUserIDByMisskeyAccount :one
SELECT user_id FROM misskey_links
WHERE misskey_instance = $1 AND misskey_user_id = $2
`

type GetUserIDByMisskeyAccountParams struct {
	MisskeyInstance string
	MisskeyUserID   string
}

func (q *Queries) GetUserIDByMisskeyAccount(ctx context.Context, arg GetUserIDByMisskeyAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByMisskeyAccount, arg.MisskeyInstance, arg.MisskeyUserID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}
