// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID          int64
	PostID      int64
	AuthorID    sql.NullInt64
	AuthorName  sql.NullString
	Body        string
	ParentID    sql.NullInt64
	CreatedAt   time.Time
	WpCommentID sql.NullInt64
}

type Medium struct {
	ID             int64
	UploaderID     sql.NullInt64
	Filename       string
	StoragePath    string
	ThumbnailPath  sql.NullString
	MimeType       string
	ByteSize       sql.NullInt64
	Width          sql.NullInt32
	Height         sql.NullInt32
	AttachedPostID sql.NullInt64
	CreatedAt      time.Time
	WpAttachmentID sql.NullInt64
}

type Post struct {
	ID          int64
	AuthorID    int64
	Title       string
	BodyHtml    string
	BodyMd      sql.NullString
	BodySource  sql.NullString
	Visibility  string
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	WpPostID    sql.NullInt64
}

type ReadMarker struct {
	UserID      int64
	PostsSeenAt time.Time
}

type Session struct {
	ID        string
	UserID    int64
	Verified  bool
	ExpiresAt time.Time
	CreatedAt time.Time
}

type TotpSecret struct {
	UserID    int64
	Secret    string
	Verified  bool
	CreatedAt time.Time
}

type User struct {
	ID           int64
	Login        string
	Email        string
	DisplayName  string
	PasswordHash string
	AvatarPath   sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	WpUserID     sql.NullInt64
}

type WebauthnCredential struct {
	ID                 string
	UserID             int64
	Name               string
	PublicKey          []byte
	AttestationType    sql.NullString
	Aaguid             []byte
	SignCount          int64
	Transports         []string
	CreatedAt          time.Time
	FlagBackupEligible bool
	FlagBackupState    bool
}
