// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package dbq

import (
	"context"
	"database/sql"
	"time"
)

const countPostsByAuthor = `-- name: CountPostsByAuthor :one
SELECT COUNT(*)::int FROM posts
WHERE author_id = $1
  AND (visibility = 'public' OR (visibility = 'private' AND author_id = $2))
`

type CountPostsByAuthorParams struct {
	AuthorID   int64
	AuthorID_2 int64
}

func (q *Queries) CountPostsByAuthor(ctx context.Context, arg CountPostsByAuthorParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countPostsByAuthor, arg.AuthorID, arg.AuthorID_2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnreadPublicPosts = `-- name: CountUnreadPublicPosts :one
SELECT COUNT(*)::int FROM posts
WHERE visibility = 'public'
  AND author_id != $1
  AND COALESCE(published_at, created_at) > $2
`

type CountUnreadPublicPostsParams struct {
	AuthorID    int64
	PublishedAt sql.NullTime
}

func (q *Queries) CountUnreadPublicPosts(ctx context.Context, arg CountUnreadPublicPostsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countUnreadPublicPosts, arg.AuthorID, arg.PublishedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countVisiblePosts = `-- name: CountVisiblePosts :one
SELECT COUNT(*)::int FROM posts
WHERE visibility = 'public'
   OR (visibility = 'private' AND author_id = $1)
`

func (q *Queries) CountVisiblePosts(ctx context.Context, authorID int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, countVisiblePosts, authorID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, title, body_html, body_md, visibility, published_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreatePostParams struct {
	AuthorID    int64
	Title       string
	BodyHtml    string
	BodyMd      sql.NullString
	Visibility  string
	PublishedAt sql.NullTime
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.AuthorID,
		arg.Title,
		arg.BodyHtml,
		arg.BodyMd,
		arg.Visibility,
		arg.PublishedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePost = `-- name: DeletePost :execrows
DELETE FROM posts WHERE id = $1 AND author_id = $2
`

type DeletePostParams struct {
	ID       int64
	AuthorID int64
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePost, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPost = `-- name: GetPost :one
SELECT p.id, p.author_id, u.display_name AS author_name, u.avatar_path AS author_avatar,
       p.title, p.body_html, p.body_md, p.visibility,
       p.published_at, p.created_at,
       (SELECT COUNT(*) FROM comments c WHERE c.post_id = p.id)::int AS comment_count
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.id = $1
  AND (p.visibility = 'public' OR (p.visibility = 'private' AND p.author_id = $2))
`

type GetPostParams struct {
	ID       int64
	AuthorID int64
}

type GetPostRow struct {
	ID           int64
	AuthorID     int64
	AuthorName   string
	AuthorAvatar sql.NullString
	Title        string
	BodyHtml     string
	BodyMd       sql.NullString
	Visibility   string
	PublishedAt  sql.NullTime
	CreatedAt    time.Time
	CommentCount int32
}

func (q *Queries) GetPost(ctx context.Context, arg GetPostParams) (GetPostRow, error) {
	row := q.db.QueryRowContext(ctx, getPost, arg.ID, arg.AuthorID)
	var i GetPostRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.Title,
		&i.BodyHtml,
		&i.BodyMd,
		&i.Visibility,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.CommentCount,
	)
	return i, err
}

const getPostForAuthorization = `-- name: GetPostForAuthorization :one
SELECT author_id, visibility, title FROM posts WHERE id = $1
`

type GetPostForAuthorizationRow struct {
	AuthorID   int64
	Visibility string
	Title      string
}

func (q *Queries) GetPostForAuthorization(ctx context.Context, id int64) (GetPostForAuthorizationRow, error) {
	row := q.db.QueryRowContext(ctx, getPostForAuthorization, id)
	var i GetPostForAuthorizationRow
	err := row.Scan(&i.AuthorID, &i.Visibility, &i.Title)
	return i, err
}

const listDrafts = `-- name: ListDrafts :many
SELECT p.id, p.author_id, u.display_name AS author_name, u.avatar_path AS author_avatar,
       p.title, p.body_html, p.visibility,
       p.published_at, p.created_at,
       (SELECT COUNT(*) FROM comments c WHERE c.post_id = p.id)::int AS comment_count
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.visibility = 'draft' AND p.author_id = $1
ORDER BY p.created_at DESC
`

type ListDraftsRow struct {
	ID           int64
	AuthorID     int64
	AuthorName   string
	AuthorAvatar sql.NullString
	Title        string
	BodyHtml     string
	Visibility   string
	PublishedAt  sql.NullTime
	CreatedAt    time.Time
	CommentCount int32
}

func (q *Queries) ListDrafts(ctx context.Context, authorID int64) ([]ListDraftsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDrafts, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftsRow{}
	for rows.Next() {
		var i ListDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.Title,
			&i.BodyHtml,
			&i.Visibility,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT p.id, p.author_id, u.display_name AS author_name, u.avatar_path AS author_avatar,
       p.title, p.body_html, p.visibility,
       p.published_at, p.created_at,
       (SELECT COUNT(*) FROM comments c WHERE c.post_id = p.id)::int AS comment_count
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.visibility = 'public'
   OR (p.visibility = 'private' AND p.author_id = $1)
ORDER BY p.published_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListPostsParams struct {
	AuthorID int64
	Limit    int32
	Offset   int32
}

type ListPostsRow struct {
	ID           int64
	AuthorID     int64
	AuthorName   string
	AuthorAvatar sql.NullString
	Title        string
	BodyHtml     string
	Visibility   string
	PublishedAt  sql.NullTime
	CreatedAt    time.Time
	CommentCount int32
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRow{}
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.Title,
			&i.BodyHtml,
			&i.Visibility,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT p.id, p.author_id, u.display_name AS author_name, u.avatar_path AS author_avatar,
       p.title, p.body_html, p.visibility,
       p.published_at, p.created_at,
       (SELECT COUNT(*) FROM comments c WHERE c.post_id = p.id)::int AS comment_count
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.author_id = $1
  AND (p.visibility = 'public' OR (p.visibility = 'private' AND p.author_id = $2))
ORDER BY p.published_at DESC NULLS LAST
LIMIT $3 OFFSET $4
`

type ListPostsByAuthorParams struct {
	AuthorID   int64
	AuthorID_2 int64
	Limit      int32
	Offset     int32
}

type ListPostsByAuthorRow struct {
	ID           int64
	AuthorID     int64
	AuthorName   string
	AuthorAvatar sql.NullString
	Title        string
	BodyHtml     string
	Visibility   string
	PublishedAt  sql.NullTime
	CreatedAt    time.Time
	CommentCount int32
}

func (q *Queries) ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]ListPostsByAuthorRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByAuthor,
		arg.AuthorID,
		arg.AuthorID_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByAuthorRow{}
	for rows.Next() {
		var i ListPostsByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.Title,
			&i.BodyHtml,
			&i.Visibility,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPosts = `-- name: SearchPosts :many
SELECT p.id, p.author_id, u.display_name AS author_name, u.avatar_path AS author_avatar,
       p.title, p.body_html, p.visibility,
       p.published_at, p.created_at,
       (SELECT COUNT(*) FROM comments c WHERE c.post_id = p.id)::int AS comment_count
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE (p.visibility = 'public' OR (p.visibility = 'private' AND p.author_id = $1))
  AND (p.title ILIKE $2 OR p.body_html ILIKE $2)
ORDER BY p.published_at DESC NULLS LAST
LIMIT 50
`

type SearchPostsParams struct {
	AuthorID int64
	Title    string
}

type SearchPostsRow struct {
	ID           int64
	AuthorID     int64
	AuthorName   string
	AuthorAvatar sql.NullString
	Title        string
	BodyHtml     string
	Visibility   string
	PublishedAt  sql.NullTime
	CreatedAt    time.Time
	CommentCount int32
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPosts, arg.AuthorID, arg.Title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostsRow{}
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.Title,
			&i.BodyHtml,
			&i.Visibility,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostBody = `-- name: UpdatePostBody :exec
UPDATE posts SET body_html = $1 WHERE id = $2
`

type UpdatePostBodyParams struct {
	BodyHtml string
	ID       int64
}

func (q *Queries) UpdatePostBody(ctx context.Context, arg UpdatePostBodyParams) error {
	_, err := q.db.ExecContext(ctx, updatePostBody, arg.BodyHtml, arg.ID)
	return err
}

const updatePostBodyMD = `-- name: UpdatePostBodyMD :exec
UPDATE posts SET body_md = $1 WHERE id = $2
`

type UpdatePostBodyMDParams struct {
	BodyMd sql.NullString
	ID     int64
}

func (q *Queries) UpdatePostBodyMD(ctx context.Context, arg UpdatePostBodyMDParams) error {
	_, err := q.db.ExecContext(ctx, updatePostBodyMD, arg.BodyMd, arg.ID)
	return err
}

const updatePostTitle = `-- name: UpdatePostTitle :exec
UPDATE posts SET title = $1 WHERE id = $2
`

type UpdatePostTitleParams struct {
	Title string
	ID    int64
}

func (q *Queries) UpdatePostTitle(ctx context.Context, arg UpdatePostTitleParams) error {
	_, err := q.db.ExecContext(ctx, updatePostTitle, arg.Title, arg.ID)
	return err
}

const updatePostVisibility = `-- name: UpdatePostVisibility :exec
UPDATE posts SET visibility = $1, published_at = COALESCE(published_at, CASE WHEN $1 = 'draft' THEN NULL ELSE NOW() END) WHERE id = $2
`

type UpdatePostVisibilityParams struct {
	Visibility string
	ID         int64
}

func (q *Queries) UpdatePostVisibility(ctx context.Context, arg UpdatePostVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, updatePostVisibility, arg.Visibility, arg.ID)
	return err
}
