// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	ConfirmTOTP(ctx context.Context, userID int64) error
	CountPostsByAuthor(ctx context.Context, arg CountPostsByAuthorParams) (int32, error)
	CountUnreadPublicPosts(ctx context.Context, arg CountUnreadPublicPostsParams) (int32, error)
	CountVisiblePosts(ctx context.Context, authorID int64) (int32, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (int64, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (int64, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error
	DeleteComment(ctx context.Context, arg DeleteCommentParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMedia(ctx context.Context, id int64) error
	DeletePost(ctx context.Context, arg DeletePostParams) (int64, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error
	DisableTOTP(ctx context.Context, userID int64) error
	ExtendSessionExpiry(ctx context.Context, arg ExtendSessionExpiryParams) error
	GetMediaForDelete(ctx context.Context, arg GetMediaForDeleteParams) (GetMediaForDeleteRow, error)
	GetMember(ctx context.Context, id int64) (GetMemberRow, error)
	GetPost(ctx context.Context, arg GetPostParams) (GetPostRow, error)
	GetPostForAuthorization(ctx context.Context, id int64) (GetPostForAuthorizationRow, error)
	GetPostTitle(ctx context.Context, id int64) (string, error)
	GetReadMarker(ctx context.Context, userID int64) (time.Time, error)
	GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error)
	GetUnverifiedTOTPSecret(ctx context.Context, userID int64) (string, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error)
	GetUserPasswordHash(ctx context.Context, id int64) (string, error)
	GetVerifiedTOTPSecret(ctx context.Context, userID int64) (string, error)
	ListComments(ctx context.Context, postID int64) ([]ListCommentsRow, error)
	ListDrafts(ctx context.Context, authorID int64) ([]ListDraftsRow, error)
	ListMediaByUploader(ctx context.Context, uploaderID sql.NullInt64) ([]ListMediaByUploaderRow, error)
	ListMembers(ctx context.Context) ([]ListMembersRow, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error)
	ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]ListPostsByAuthorRow, error)
	ListWebAuthnCredentials(ctx context.Context, userID int64) ([]ListWebAuthnCredentialsRow, error)
	LoadWebAuthnCredentials(ctx context.Context, userID int64) ([]LoadWebAuthnCredentialsRow, error)
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error)
	UpdatePostBody(ctx context.Context, arg UpdatePostBodyParams) error
	UpdatePostBodyMD(ctx context.Context, arg UpdatePostBodyMDParams) error
	UpdatePostTitle(ctx context.Context, arg UpdatePostTitleParams) error
	UpdatePostVisibility(ctx context.Context, arg UpdatePostVisibilityParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWebAuthnSignCount(ctx context.Context, arg UpdateWebAuthnSignCountParams) error
	UpsertReadMarker(ctx context.Context, userID int64) error
	UpsertTOTPSecret(ctx context.Context, arg UpsertTOTPSecretParams) error
	UserHas2FA(ctx context.Context, userID int64) (UserHas2FARow, error)
	VerifySession(ctx context.Context, arg VerifySessionParams) error
}

var _ Querier = (*Queries)(nil)
