// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read_markers.sql

package dbq

import (
	"context"
	"time"
)

const getReadMarker = `-- name: GetReadMarker :one
SELECT posts_seen_at FROM read_markers WHERE user_id = $1
`

func (q *Queries) GetReadMarker(ctx context.Context, userID int64) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getReadMarker, userID)
	var posts_seen_at time.Time
	err := row.Scan(&posts_seen_at)
	return posts_seen_at, err
}

const upsertReadMarker = `-- name: UpsertReadMarker :exec
INSERT INTO read_markers (user_id, posts_seen_at)
VALUES ($1, NOW())
ON CONFLICT (user_id) DO UPDATE SET posts_seen_at = NOW()
`

func (q *Queries) UpsertReadMarker(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, upsertReadMarker, userID)
	return err
}
