// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbq

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, verified, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	ID        string
	UserID    int64
	Verified  bool
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Verified,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const extendSessionExpiry = `-- name: ExtendSessionExpiry :exec
UPDATE sessions SET expires_at = $1 WHERE id = $2
`

type ExtendSessionExpiryParams struct {
	ExpiresAt time.Time
	ID        string
}

func (q *Queries) ExtendSessionExpiry(ctx context.Context, arg ExtendSessionExpiryParams) error {
	_, err := q.db.ExecContext(ctx, extendSessionExpiry, arg.ExpiresAt, arg.ID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.user_id, s.expires_at, u.login, u.display_name, u.avatar_path,
       EXISTS(SELECT 1 FROM totp_secrets WHERE user_id = u.id AND verified = true) AS has_totp,
       EXISTS(SELECT 1 FROM webauthn_credentials WHERE user_id = u.id) AS has_webauthn
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1 AND s.expires_at > NOW() AND s.verified = $2
`

type GetSessionParams struct {
	ID       string
	Verified bool
}

type GetSessionRow struct {
	UserID      int64
	ExpiresAt   time.Time
	Login       string
	DisplayName string
	AvatarPath  sql.NullString
	HasTotp     bool
	HasWebauthn bool
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.ID, arg.Verified)
	var i GetSessionRow
	err := row.Scan(
		&i.UserID,
		&i.ExpiresAt,
		&i.Login,
		&i.DisplayName,
		&i.AvatarPath,
		&i.HasTotp,
		&i.HasWebauthn,
	)
	return i, err
}

const verifySession = `-- name: VerifySession :exec
UPDATE sessions SET verified = true, expires_at = $1 WHERE id = $2
`

type VerifySessionParams struct {
	ExpiresAt time.Time
	ID        string
}

func (q *Queries) VerifySession(ctx context.Context, arg VerifySessionParams) error {
	_, err := q.db.ExecContext(ctx, verifySession, arg.ExpiresAt, arg.ID)
	return err
}
