// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: totp.sql

package dbq

import (
	"context"
)

const confirmTOTP = `-- name: ConfirmTOTP :exec
UPDATE totp_secrets SET verified = true WHERE user_id = $1
`

func (q *Queries) ConfirmTOTP(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, confirmTOTP, userID)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
DELETE FROM totp_secrets WHERE user_id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, disableTOTP, userID)
	return err
}

const getUnverifiedTOTPSecret = `-- name: GetUnverifiedTOTPSecret :one
SELECT secret FROM totp_secrets WHERE user_id = $1 AND verified = false
`

func (q *Queries) GetUnverifiedTOTPSecret(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUnverifiedTOTPSecret, userID)
	var secret string
	err := row.Scan(&secret)
	return secret, err
}

const getVerifiedTOTPSecret = `-- name: GetVerifiedTOTPSecret :one
SELECT secret FROM totp_secrets WHERE user_id = $1 AND verified = true
`

func (q *Queries) GetVerifiedTOTPSecret(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getVerifiedTOTPSecret, userID)
	var secret string
	err := row.Scan(&secret)
	return secret, err
}

const upsertTOTPSecret = `-- name: UpsertTOTPSecret :exec
INSERT INTO totp_secrets (user_id, secret, verified)
VALUES ($1, $2, false)
ON CONFLICT (user_id) DO UPDATE SET secret = EXCLUDED.secret, verified = false
`

type UpsertTOTPSecretParams struct {
	UserID int64
	Secret string
}

func (q *Queries) UpsertTOTPSecret(ctx context.Context, arg UpsertTOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertTOTPSecret, arg.UserID, arg.Secret)
	return err
}
