// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbq

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (login, email, display_name, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateUserParams struct {
	Login        string
	Email        string
	DisplayName  string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Login,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMember = `-- name: GetMember :one
SELECT u.id, u.login, u.display_name, u.avatar_path, u.created_at,
       (SELECT COUNT(*) FROM posts WHERE author_id = u.id AND visibility != 'draft')::int AS post_count,
       (SELECT COUNT(*) FROM comments WHERE author_id = u.id)::int AS comment_count
FROM users u WHERE u.id = $1
`

type GetMemberRow struct {
	ID           int64
	Login        string
	DisplayName  string
	AvatarPath   sql.NullString
	CreatedAt    time.Time
	PostCount    int32
	CommentCount int32
}

func (q *Queries) GetMember(ctx context.Context, id int64) (GetMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getMember, id)
	var i GetMemberRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.AvatarPath,
		&i.CreatedAt,
		&i.PostCount,
		&i.CommentCount,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, email, display_name, avatar_path, created_at
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID          int64
	Login       string
	Email       string
	DisplayName string
	AvatarPath  sql.NullString
	CreatedAt   time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.AvatarPath,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, email, display_name, password_hash, avatar_path
FROM users WHERE login = $1
`

type GetUserByLoginRow struct {
	ID           int64
	Login        string
	Email        string
	DisplayName  string
	PasswordHash string
	AvatarPath   sql.NullString
}

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarPath,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const listMembers = `-- name: ListMembers :many
SELECT u.id, u.login, u.display_name, u.avatar_path, u.created_at,
       (SELECT COUNT(*) FROM posts WHERE author_id = u.id AND visibility != 'draft')::int AS post_count,
       (SELECT COUNT(*) FROM comments WHERE author_id = u.id)::int AS comment_count
FROM users u
ORDER BY u.created_at
`

type ListMembersRow struct {
	ID           int64
	Login        string
	DisplayName  string
	AvatarPath   sql.NullString
	CreatedAt    time.Time
	PostCount    int32
	CommentCount int32
}

func (q *Queries) ListMembers(ctx context.Context) ([]ListMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.DisplayName,
			&i.AvatarPath,
			&i.CreatedAt,
			&i.PostCount,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar_path = $1 WHERE id = $2
`

type UpdateUserAvatarParams struct {
	AvatarPath sql.NullString
	ID         int64
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar, arg.AvatarPath, arg.ID)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users SET display_name = $1 WHERE id = $2
`

type UpdateUserDisplayNameParams struct {
	DisplayName string
	ID          int64
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDisplayName, arg.DisplayName, arg.ID)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $1 WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string
	ID    int64
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const userHas2FA = `-- name: UserHas2FA :one
SELECT
  EXISTS(SELECT 1 FROM totp_secrets ts WHERE ts.user_id = $1 AND ts.verified = true) AS has_totp,
  EXISTS(SELECT 1 FROM webauthn_credentials wc WHERE wc.user_id = $1) AS has_webauthn
`

type UserHas2FARow struct {
	HasTotp     bool
	HasWebauthn bool
}

func (q *Queries) UserHas2FA(ctx context.Context, userID int64) (UserHas2FARow, error) {
	row := q.db.QueryRowContext(ctx, userHas2FA, userID)
	var i UserHas2FARow
	err := row.Scan(&i.HasTotp, &i.HasWebauthn)
	return i, err
}
