// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webauthn.sql

package dbq

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :exec
INSERT INTO webauthn_credentials
  (id, user_id, name, public_key, attestation_type, sign_count,
   transports, flag_backup_eligible, flag_backup_state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateWebAuthnCredentialParams struct {
	ID                 string
	UserID             int64
	Name               string
	PublicKey          []byte
	AttestationType    sql.NullString
	SignCount          int64
	Transports         []string
	FlagBackupEligible bool
	FlagBackupState    bool
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createWebAuthnCredential,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.PublicKey,
		arg.AttestationType,
		arg.SignCount,
		pq.Array(arg.Transports),
		arg.FlagBackupEligible,
		arg.FlagBackupState,
	)
	return err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM webauthn_credentials WHERE id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID     string
	UserID int64
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	return err
}

const listWebAuthnCredentials = `-- name: ListWebAuthnCredentials :many
SELECT id, name, created_at
FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at
`

type ListWebAuthnCredentialsRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) ListWebAuthnCredentials(ctx context.Context, userID int64) ([]ListWebAuthnCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWebAuthnCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebAuthnCredentialsRow{}
	for rows.Next() {
		var i ListWebAuthnCredentialsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadWebAuthnCredentials = `-- name: LoadWebAuthnCredentials :many
SELECT id, public_key, attestation_type, sign_count, transports,
       flag_backup_eligible, flag_backup_state
FROM webauthn_credentials WHERE user_id = $1
`

type LoadWebAuthnCredentialsRow struct {
	ID                 string
	PublicKey          []byte
	AttestationType    sql.NullString
	SignCount          int64
	Transports         []string
	FlagBackupEligible bool
	FlagBackupState    bool
}

func (q *Queries) LoadWebAuthnCredentials(ctx context.Context, userID int64) ([]LoadWebAuthnCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, loadWebAuthnCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadWebAuthnCredentialsRow{}
	for rows.Next() {
		var i LoadWebAuthnCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicKey,
			&i.AttestationType,
			&i.SignCount,
			pq.Array(&i.Transports),
			&i.FlagBackupEligible,
			&i.FlagBackupState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebAuthnSignCount = `-- name: UpdateWebAuthnSignCount :exec
UPDATE webauthn_credentials SET sign_count = $1 WHERE id = $2
`

type UpdateWebAuthnSignCountParams struct {
	SignCount int64
	ID        string
}

func (q *Queries) UpdateWebAuthnSignCount(ctx context.Context, arg UpdateWebAuthnSignCountParams) error {
	_, err := q.db.ExecContext(ctx, updateWebAuthnSignCount, arg.SignCount, arg.ID)
	return err
}
